
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TOK1 = 8;
  public static final int MINUS = 3;
  public static final int INT = 13;
  public static final int COST = 14;
  public static final int SC = 4;
  public static final int CM = 5;
  public static final int STAR = 2;
  public static final int EOF = 0;
  public static final int EURO = 11;
  public static final int SEP = 7;
  public static final int PERC = 6;
  public static final int error = 1;
  public static final int TOK3 = 10;
  public static final int NAME = 12;
  public static final int TOK2 = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STAR",
  "MINUS",
  "SC",
  "CM",
  "PERC",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "EURO",
  "NAME",
  "INT",
  "COST"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[8]=new String("TOK1");
		TT[3]=new String("MINUS");
		TT[13]=new String("INT");
		TT[14]=new String("COST");
		TT[4]=new String("SC");
		TT[5]=new String("CM");
		TT[2]=new String("STAR");
		TT[0]=new String("EOF");
		TT[11]=new String("EURO");
		TT[7]=new String("SEP");
		TT[6]=new String("PERC");
		TT[1]=new String("error");
		TT[10]=new String("TOK3");
		TT[12]=new String("NAME");
		TT[9]=new String("TOK2");
	}
public String getTT(int i){return TT[i];}
}

