
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SC = 6;
  public static final int BOOK = 4;
  public static final int CO = 5;
  public static final int WRITER = 3;
  public static final int INVALID = 9;
  public static final int USER = 7;
  public static final int LOAN = 8;
  public static final int EOF = 0;
  public static final int SEP = 2;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "WRITER",
  "BOOK",
  "CO",
  "SC",
  "USER",
  "LOAN",
  "INVALID"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[6]=new String("SC");
		TT[4]=new String("BOOK");
		TT[5]=new String("CO");
		TT[3]=new String("WRITER");
		TT[9]=new String("INVALID");
		TT[7]=new String("USER");
		TT[8]=new String("LOAN");
		TT[0]=new String("EOF");
		TT[2]=new String("SEP");
		TT[1]=new String("error");
	}
public String getTT(int i){return TT[i];}
}

