
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RO = 8;
  public static final int EOF = 0;
  public static final int ATOM = 3;
  public static final int VAR = 4;
  public static final int RC = 9;
  public static final int DOT = 7;
  public static final int error = 1;
  public static final int COM = 10;
  public static final int RS = 6;
  public static final int COMMENT = 2;
  public static final int IS = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMENT",
  "ATOM",
  "VAR",
  "IS",
  "RS",
  "DOT",
  "RO",
  "RC",
  "COM"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[8]=new String("RO");
		TT[0]=new String("EOF");
		TT[3]=new String("ATOM");
		TT[4]=new String("VAR");
		TT[9]=new String("RC");
		TT[7]=new String("DOT");
		TT[1]=new String("error");
		TT[10]=new String("COM");
		TT[6]=new String("RS");
		TT[2]=new String("COMMENT");
		TT[5]=new String("IS");
	}
public String getTT(int i){return TT[i];}
}

