
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 23;
  public static final int OR = 24;
  public static final int CM = 3;
  public static final int THEN = 8;
  public static final int RO = 19;
  public static final int NOT = 10;
  public static final int END = 6;
  public static final int FI = 9;
  public static final int TRUE = 12;
  public static final int IF = 7;
  public static final int RC = 20;
  public static final int STRING = 22;
  public static final int EOF = 0;
  public static final int TOK3 = 18;
  public static final int TOK2 = 17;
  public static final int FALSE = 13;
  public static final int SEP = 15;
  public static final int TOK1 = 16;
  public static final int DOT = 21;
  public static final int PRINT = 14;
  public static final int error = 1;
  public static final int EQ = 11;
  public static final int START = 5;
  public static final int SC = 2;
  public static final int SIZE = 25;
  public static final int HOUSE = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SC",
  "CM",
  "HOUSE",
  "START",
  "END",
  "IF",
  "THEN",
  "FI",
  "NOT",
  "EQ",
  "TRUE",
  "FALSE",
  "PRINT",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "RO",
  "RC",
  "DOT",
  "STRING",
  "AND",
  "OR",
  "SIZE"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[23]=new String("AND");
		TT[24]=new String("OR");
		TT[3]=new String("CM");
		TT[8]=new String("THEN");
		TT[19]=new String("RO");
		TT[10]=new String("NOT");
		TT[6]=new String("END");
		TT[9]=new String("FI");
		TT[12]=new String("TRUE");
		TT[7]=new String("IF");
		TT[20]=new String("RC");
		TT[22]=new String("STRING");
		TT[0]=new String("EOF");
		TT[18]=new String("TOK3");
		TT[17]=new String("TOK2");
		TT[13]=new String("FALSE");
		TT[15]=new String("SEP");
		TT[16]=new String("TOK1");
		TT[21]=new String("DOT");
		TT[14]=new String("PRINT");
		TT[1]=new String("error");
		TT[11]=new String("EQ");
		TT[5]=new String("START");
		TT[2]=new String("SC");
		TT[25]=new String("SIZE");
		TT[4]=new String("HOUSE");
	}
public String getTT(int i){return TT[i];}
}

