
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GEQ = 23;
  public static final int AND = 18;
  public static final int ROUND_OPEN = 14;
  public static final int DOUBLE_TYPE = 26;
  public static final int ELSE = 28;
  public static final int SEMICOLON = 9;
  public static final int BRACE_CLOSE = 17;
  public static final int PLUS = 2;
  public static final int INT = 31;
  public static final int OR = 19;
  public static final int EQUAL = 6;
  public static final int WHILE = 29;
  public static final int LOWER_THAN_ELSE = 34;
  public static final int STAR = 4;
  public static final int NOT = 20;
  public static final int MAJOR = 8;
  public static final int BRACE_OPEN = 16;
  public static final int IF = 27;
  public static final int ID = 33;
  public static final int COMMA = 11;
  public static final int EOF = 0;
  public static final int SQUARE_OPEN = 12;
  public static final int MINOR = 7;
  public static final int MINUS = 3;
  public static final int PRINT = 30;
  public static final int error = 1;
  public static final int DOT = 10;
  public static final int INT_TYPE = 25;
  public static final int EQ = 21;
  public static final int LEQ = 22;
  public static final int DASH = 5;
  public static final int NEQ = 24;
  public static final int SQUARE_CLOSE = 13;
  public static final int ROUND_CLOSE = 15;
  public static final int DOUBLE = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "STAR",
  "DASH",
  "EQUAL",
  "MINOR",
  "MAJOR",
  "SEMICOLON",
  "DOT",
  "COMMA",
  "SQUARE_OPEN",
  "SQUARE_CLOSE",
  "ROUND_OPEN",
  "ROUND_CLOSE",
  "BRACE_OPEN",
  "BRACE_CLOSE",
  "AND",
  "OR",
  "NOT",
  "EQ",
  "LEQ",
  "GEQ",
  "NEQ",
  "INT_TYPE",
  "DOUBLE_TYPE",
  "IF",
  "ELSE",
  "WHILE",
  "PRINT",
  "INT",
  "DOUBLE",
  "ID",
  "LOWER_THAN_ELSE"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[23]=new String("GEQ");
		TT[18]=new String("AND");
		TT[14]=new String("ROUND_OPEN");
		TT[26]=new String("DOUBLE_TYPE");
		TT[28]=new String("ELSE");
		TT[9]=new String("SEMICOLON");
		TT[17]=new String("BRACE_CLOSE");
		TT[2]=new String("PLUS");
		TT[31]=new String("INT");
		TT[19]=new String("OR");
		TT[6]=new String("EQUAL");
		TT[29]=new String("WHILE");
		TT[34]=new String("LOWER_THAN_ELSE");
		TT[4]=new String("STAR");
		TT[20]=new String("NOT");
		TT[8]=new String("MAJOR");
		TT[16]=new String("BRACE_OPEN");
		TT[27]=new String("IF");
		TT[33]=new String("ID");
		TT[11]=new String("COMMA");
		TT[0]=new String("EOF");
		TT[12]=new String("SQUARE_OPEN");
		TT[7]=new String("MINOR");
		TT[3]=new String("MINUS");
		TT[30]=new String("PRINT");
		TT[1]=new String("error");
		TT[10]=new String("DOT");
		TT[25]=new String("INT_TYPE");
		TT[21]=new String("EQ");
		TT[22]=new String("LEQ");
		TT[5]=new String("DASH");
		TT[24]=new String("NEQ");
		TT[13]=new String("SQUARE_CLOSE");
		TT[15]=new String("ROUND_CLOSE");
		TT[32]=new String("DOUBLE");
	}
public String getTT(int i){return TT[i];}
}

